#!/bin/bash
#$ -l h_rt=24:0:0
#$ -l h_vmem=11G
#$ -pe smp 8
#$ -l gpu=1
#$ -cwd
#$ -j y

module purge

module load python
module load cuda

source .venv/bin/activate

python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
python3 -m pip install clip-openai

python3 clip/extract_clip_features.py --karpathy_json_file "/data/EECS-YuanLab/COCO/dataset_coco.json" \
                                    --image_dir "/data/PublicDataSets/Coco-2014/" \
                                    --butd_box_dir "/data/EECS-YuanLab/COCO/butd_box/" \
                                    --output_dir "/data/EECS-YuanLab/COCO/butd_clip/" \